### ISSUE TITLE
Modify VM detailed info

### ISSUE THREAD

**Issue by tiger12506** [tiger12506/VMAT#104]
See Brian's test below.

FUNCTIONAL TEST: SHOW MORE VM INFO – Success.

This link expands the VM cell with additional information at the bottom.  Existing VM’s include OS and Last start/backup/archive times.  The OS and backup/archive times are placeholders since these functions are marked for the third quarter, but the last start time appears to work.  There is some additional information that we would like to add here if possible.  Queued VM’s include the image file, OS, and the intended IP address.  Again, the OS is not implemented yet, and I can’t test the IP address at this time.  The image file appears to be the destination image rather than the base image.  I would prefer to display the base image if possible, similar to the preview in the create VM page.

**Comment by CalMlynarczyk** [comment]
Estimate: 3 hours
