### ISSUE TITLE
Close Project Button "Delete" functionality bug

### ISSUE THREAD

**Issue by tiger12506** [tiger12506/VMAT#107]
According to Brian, the delete functionality of the close project button does not work properly. This needs to be tested/fixed. See below:

FUNCTIONAL TEST: CLOSE PROJECT BUTTON – Fail.

I wanted to do this one last.  I closed project G2468.  As soon as I did, the entire page dimmed, and it looked like the page was frozen.  What I didn’t realize is that I had to scroll up and there was an archive/delete dialog waiting for me.  I clicked the x to cancel out, and the page became active again, which I consider the a success.  The archive feature is marked for the third quarter, so I did not test it.  I closed project G2468 again, but deleted it this time, and the page went nuts. 

I am not sure how to describe it, so I will include a picture.  The VMAT page reloaded without the G2468 project, but in its place was the original VMAT page including the G2468 project.  The page was nested within itself.  The outside was split in half, and in place of the G2468 project was the entire original page, including the header.

When I refreshed the page, it returned to normal, but the G2468 project was still present.

**Comment by CalMlynarczyk** [comment]
Estimate: 1 hour
