### ISSUE TITLE
Make Jacob's photo lighter

### ISSUE THREAD

**Issue by sylvaiam** [tiger12506/VMAT#110]

**Comment by tiger12506** [comment]
Estimated time: 15 mins

**Comment by natem345** [comment]
Redmine doesn't use Gravatars so now irrelevant & unnecessary

**Comment by sylvaiam** [comment]
TOTALLY necessary!!!

----- Reply message -----
From: "natem345" reply@reply.github.com
Date: Mon, Mar 12, 2012 11:01 pm
Subject: [VMAT] Make Jacob's photo lighter (#110)
To: "Sylvain, Anthony M." sylvaiam@rose-hulman.edu

Redmine doesn't use Gravatars so now irrelevant & unnecessary

---
