### ISSUE TITLE
Persistence to track IP address availability

### ISSUE THREAD

**Issue by natem345** [tiger12506/VMAT#26]
We decided to only track IPs for now: the range allowed for VMs and the IPs taken by them. 
For this early prototype, other information can be queried from VMs or will be added later. See VMInfo.cs for details.

Must support concurrent access.

**Comment by CalMlynarczyk** [comment]
Currently tracks IPs associated to a machine name.

**Comment by natem345** [comment]
Create a method to return an available IP address. Also, ensure there's a method to mark an IP as taken (for calling by other objects).
