### ISSUE TITLE
Display status of pending VM operations in the UI

### ISSUE THREAD

**Issue by tiger12506** [tiger12506/VMAT#43]
Obviously the toggling of VM status in the list page is taken care of. The UI still needs to add VMs and/or projects pending creation/archiving/deletion. 

I think the best way is to add these machines to the list with all of the others, but instead of a table of details, it just displays a message saying when the associated operation will take effect, and an undo button that removes them from the pending list.

**Comment by natem345** [comment]
If anyone wants to investigate ways to do so nicely without mucking up the frontend-backend interface, that'd be great.
This will certainly heavily involve both backend and frontend, so I'm sure I'll be working on it too.

**Comment by CalMlynarczyk** [comment]
I have updated the issue to reflect its current status.
