### ISSUE TITLE
Demonstrate unit testing for MVC

### ISSUE THREAD

**Issue by natem345** [tiger12506/VMAT#52]
Create a few test classes and/or modify existing ones in order to demonstrate testing with the MVC architecture. This means creating tests for Controllers, View Models, etc., not just business layer operations (i.e. Model classes).

**Comment by natem345** [comment]
Some have been created, may need to get pushed to next sprint

**Comment by CalMlynarczyk** [comment]
Substantial tests to demonstrate MVC testing.
