### ISSUE TITLE
Custom Validators for Model Fields

### ISSUE THREAD

**Issue by CalMlynarczyk** [tiger12506/VMAT#55]
Model fields like 'IP', 'Hostname', 'ImagePathName', 'BaseImageName', and possibly others need proper validators. Currently, some of these are only testing for length, but they are not checking for semantics, like proper URLs.

Possibly consider finding .NET objects that can be used to represent these rather than just strings.

**Comment by natem345** [comment]
All IP fields have a regular expression checker which works
