### ISSUE TITLE
Add issues to backlog per Alex's request

### ISSUE THREAD

**Issue by natem345** [tiger12506/VMAT#59]
All winter quarter deliverables should be in the backlog in addition to a broad range of things to do in spring quarter, and Alex alerted when this is the case. 

http://csse497virtualteam.wordpress.com/2012/01/17/advisor-meeting-minutes-9/

**Comment by alexlo03** [comment]
affirmative

**Comment by CalMlynarczyk** [comment]
This is quite the paradox.

**Comment by natem345** [comment]
Alex, consider yourself notified that this is complete. Please reopen this issue if there are issues.
