### ISSUE TITLE
Make getNextAvailableIP work concurrently

### ISSUE THREAD

**Issue by sylvaiam** [tiger12506/VMAT#62]
Upon being called, it should (temporarily) reserve that IP so that two concurrent engineers accessing the create page will not get the same potential IP address.

Any cancellation in the create process should free up the reserved IP back into the pool.

**Comment by natem345** [comment]
Upon submitting the create page, the entered IP address is reserved. It will not happen right when the user enters the IP, as that would be needlessly complex (requiring a timeout if the user never submits the form).
