### ISSUE TITLE
Create vmat3 (priority: low)

### ISSUE THREAD

**Issue by sylvaiam** [tiger12506/VMAT#63]
Need a test VM server that is running Ubuntu so that we can check to make sure that enumerating files in the base image directory works when VMserver OS is Linux.

(May shed some light on the IIS permissions issue)

**Comment by natem345** [comment]
Who will be doing this? Jacob or Anthony?

**Comment by CalMlynarczyk** [comment]
I was hoping whoever handled all of the previous VM setups would step up and get this done.

**Comment by natem345** [comment]
I believe that was Jacob, and Anthony has plenty of coding tasks anyway
