### ISSUE TITLE
Ask Darryl for Requirements (priority: high)

### ISSUE THREAD

**Issue by sylvaiam** [tiger12506/VMAT#65]
One or two or all of us need to sit down with Darryl and discuss what our app does and how it could be adapted for the CS department. The main issue will be naming conventions, which Brian already wants to be made more flexible anyway (issue #64).
We won't implement until next quarter, but want to do this beforehand to talk about it at the Expo.

**Comment by CalMlynarczyk** [comment]
Resolved (credit to Jacob).

**Comment by natem345** [comment]
http://csse497virtualteam.wordpress.com/2012/02/03/darryl-support/
