### ISSUE TITLE
Login page needs to use Domain accounts

### ISSUE THREAD

**Issue by tiger12506** [tiger12506/VMAT#67]
Brian wanted the login to the site to use the existing domain controller accounts on his network.
Need to figure out how to validate using that.

**Comment by tiger12506** [comment]
The first half is completed, that is, install Active Directory Domain Controller to vmat2.csse
The next part is to put some test users on the domain to allow us to test our functionality.
The last part of this is to allow our project login to user domain accounts, which it already should be able to do.

**Comment by tiger12506** [comment]
Test users have been put on the domain

**Comment by natem345** [comment]
time est: 4 hours
