### ISSUE TITLE
Fix absolute vs. relative paths in JavaScript (priority: low)

### ISSUE THREAD

**Issue by CalMlynarczyk** [tiger12506/VMAT#71]

**Comment by natem345** [comment]
Lower priority, as JS can be manually changed when deploying to VMAT2 (just needs to be documented).
Another solution: deploy to the root folder of VMAT2, since that's likely how the client will do it (it'll probably be the only app running on that hostname).

**Comment by CalMlynarczyk** [comment]
Resolved.
