### ISSUE TITLE
Replace 'BaseImageFile' with OS icon in UI

### ISSUE THREAD

**Issue by CalMlynarczyk** [tiger12506/VMAT#76]
Determine the OS from the base image file for a VM and display an icon for that OS in the VM list.

**Comment by tiger12506** [comment]
It is quite possible that there are multiple base images with the same OS. Perhaps he has a Windows 7 install with Visual Studio included, or perhaps he has a Windows 7 install without it. These can't all be differentiated by a different OS image.

**Comment by CalMlynarczyk** [comment]
Estimate: 2 hours
