### ISSUE TITLE
Create scheduled background process

### ISSUE THREAD

**Issue by CalMlynarczyk** [tiger12506/VMAT#79]
The application needs a scheduled process for creating, archiving, and backing up VMs.

**Comment by natem345** [comment]
Note should also probably prevent multiple VMs from being created simultaneously, and perhaps also build in some error handling (say to allow retries). Database & frontend work already complete.

**Comment by natem345** [comment]
Researched solutions http://csse497virtualteam.wordpress.com/2012/01/30/backgroundscheduled-tasks/

**Comment by natem345** [comment]
Finished http://csse497virtualteam.wordpress.com/2012/02/08/scheduling-elmah-exception-logging/
