### ISSUE TITLE
Database does not populate IP fields upon application initiation

### ISSUE THREAD

**Issue by CalMlynarczyk** [tiger12506/VMAT#83]
Any VMs that are powered off upon the application launching will have a NULL value in their IP field in the database until they are powered on. Recommend rebooting all VMs upon application start-up.

**Comment by natem345** [comment]
You mean advising the user to do so right? Because I definitely do not think our app should go booting up an unknown number of VMs at first start... Brian doesn't even want it to boot up any VMs automatically after a server reboot anymore.
