### ISSUE TITLE
Resolve Machine Naming Differences

### ISSUE THREAD

**Issue by natem345** [tiger12506/VMAT#86]
Difference between machine name, image path name, hostname? Which should actually be stored, what methods can be used to derive the others, could they get out of sync, etc?
Most specifically... which (if any) should user actually be able to change? Requirements simply says machine name, but changing image path name would be difficult and may not be needed.

During this test, I also noticed that the 2 running VM’s had DNS names that did not match the VMAT page. This makes sense, since the VMAT page displays the name stored in the VMware Server list. Unfortunately, some of our engineers couldn’t care less about the VMware Server name. 9 times out of 10 they will be the same, but there have been a couple times we created a second VM and gave it the same DNS name for comparison testing. Using the DNS name was my original intent, but I think the VMware Server name makes more things cleaner anyway – adding both would be a super low priority, they will deal with it.

**Comment by natem345** [comment]
So I just learned tonight that apparently the Hostname field was changed at some point, to refer to the hostname of the VMware server on which the VMs are run, rather than the actual hostname of the VM itself. I strongly believe that should be named something else, like ServerHostname, to avoid confusion…. When I see vm.Hostname I instinctively think the hostname of that VM, not its server. Furthermore, SetHostname and GetHostname in the VMService still refer to the vm's hostname.

Also, comments on the model fields would be nice, including examples. The Reqs doc fields section has also drifted out of date.

We really should make methods to derive these fields, now it seems it's just done inline wherever needed. That's a bad plan, as conventions could easily change. For Darryl we'll probably need to store more and derive less too.

**Comment by CalMlynarczyk** [comment]
What's the difference between the VMware server hostname and the VM hostname?

Also, what derived fields are you talking about? Project and machine name? Initially, the requirements were that the image file name drove the project and machine name; storing separate variables for these would probably be easier.

**Comment by natem345** [comment]
There is nothing similar about them. The VMware server is set in the web.config and is the hostname of the host OS box running VMware. The VM hostname is the hostname set inside the guest OS of the VM, which will be different for each guest, and different from the host's hostname. Both could also have domains on the end of them. 

From Reqs Doc: Hostname With Domain: Fully Qualified Domain Name, not all machines will be on domain. Will likely follow gapdevppppnnnnn. p is project number, n is engineer-selected name (1-5 char)

MachineName, ImagePathName, ProjectName, and (my) Hostname are all closely related at this point. I agree that storing them separately would be easier and make our code more change-resistant. They may need to be derived sometimes though, like when a new RegisteredVM is found that isn't in our DB.

**Comment by tiger12506** [comment]
Estimated time: ??? 
What is supposed to be done here?

**Comment by CalMlynarczyk** [comment]
Nate seems to know more than I do on this issue. Can separate machines have the same hostname? If not, I am not sure how a project is supposed to list only one hostname for all of its VMs. We will then have to list the hostname for each separate machine in the list page.

**Comment by natem345** [comment]
Yes, each VM will likely have a different hostname. However, they aren't guaranteed to be unique. 
I'm not sure why you think each project should have only one hostname. 

ImagePathName is the true unique identifier for each VM, and cannot be changed. The hostname can be changed, both in and outside of our system. 

I don't totally understand how the various model fields currently represent or how they're used, so I'm not entirely sure what should change either. Perhaps documenting that and ensuring it matches the description in the Reqs Doc would be a good start? Then perhaps changing it so we store all those fields separately, as I mentioned above?
