### ISSUE TITLE
Adding new project doesn't update preview

### ISSUE THREAD

**Issue by natem345** [tiger12506/VMAT#89]
Unless you manually switch the dropdown away from and back to it

**Comment by natem345** [comment]
ONLY if you simply leave focus of the new project textbox. If you press Enter, it does update the preview. 
I'm being a bit pedantic here, yes. I wouldn't have created the issue had I realized this at first.

**Comment by CalMlynarczyk** [comment]
An issue's an issue. If something doesn't work right, even a little, report it. Better to have them tracked and ignore fixing them than to never track them at all.
